[project]
name = "Cyrilux"
version = "0.2.0"
description = "From raw bytes, light emerges. 要相信浪漫一如初见，永恒属于每一刻♪"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.12.0",
    "numpy>=2.4.5",
    "torchao>=0.17.0",
    "bitsandbytes>=0.43.0",
    "accelerate>=1.13.0",
    "typer>=0.15.0",
    "matplotlib>=3.10.9",
    "requests>=2.34.2",
    "pillow>=12.2.0",
    "maliang>=3.1.5",
    "PyQt6>=6.8.0",
    "ninja>=1.13.0",
]

[project.scripts]
cyrilux = "pkg.cli:app"

[tool.setuptools.packages.find]
include = [
    "pkg",
    "pkg.*",
    "pkg.device",
    "pkg.device.*",
    "model",
    "model.*",
    "dataset",
    "dataset.*",
    "pkg.cli",
    "pkg.cli.*",
    "pkg.gui",
    "pkg.gui.*",
    "model.core",
    "model.core.*",
    "model.continual",
    "model.continual.*",
]


[tool.uv.sources]
torch = [
    { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]


[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://mirrors.nju.edu.cn/pytorch/whl/cu132"
explicit = true


[tool.uv]
package = true

[tool.basedpyright]
typeCheckingMode = "standard"
reportPrivateImportUsage = "none"


[tool.ruff]
line-length = 100
target-version = "py312"

lint.ignore = ["E301", "E302", "E303", "E304", "E305", "E306", "E741", "E702"]

lint.select = [
    "F", # Pyflakes — 未定义变量、未使用导入/变量等真正错误
    "E", # pycodestyle 错误 — 基本风格问题（缩进、空行等）
    # "I", # isort — 导入排序
    # "D", # pydocstyle — 文档字符串规范（配合 Google 风格）
]

lint.per-file-ignores = { "__init__.py" = ["F401"] }

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["alm", "col", "training", "scripts"]

[tool.ruff.format]
quote-style = "double"
